project_name: tl-test-project
provider: aws
ci_cd: github-actions
domain: trml.io
terraform_version: 0.13.5
security:
  authentication:
    type: Auth0
    config:
      client_id: J41vu04B0CzNcaCGZXPkQNIAnKW92O17
      client_secret: ntrJYTVn5BvgdnDWVLqwr0nD8vJHU6KV9cLOyNoCOijthwfghRxXR0MfPShTNvtE
      oauth_callback_url: https://jupyter.trml.io/hub/oauth_callback
      scope:
      - openid
      - email
      - profile
      auth0_subdomain: dev-dswz2snx.us
  users:
    costrouc:
      uid: 1000
      primary_group: users
      secondary_groups:
      - admin
    verhulstm:
      uid: 1000001
      primary_group: users
      secondary_groups:
      - admin
  groups:
    users:
      gid: 100
    admin:
      gid: 101
default_images:
  jupyterhub: quansight/qhub-jupyterhub:1abd4efb8428a9d851b18e89b6f6e5ef94854334
  jupyterlab: quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334
  dask_worker: quansight/qhub-dask-worker:1abd4efb8428a9d851b18e89b6f6e5ef94854334
storage:
  conda_store: 20Gi
  shared_filesystem: 10Gi
amazon_web_services:
  region: us-west-2
  availability_zones:
  - us-west-2a
  - us-west-2b
  kubernetes_version: '1.14'
  node_groups:
    general:
      instance: m5.large
      min_nodes: 1
      max_nodes: 1
    user:
      instance: m5.large
      min_nodes: 1
      max_nodes: 2
    worker:
      instance: m5.large
      min_nodes: 1
      max_nodes: 2
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 1 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 1
      mem_limit: 1G
      mem_guarantee: 1G
      image: quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334
  - display_name: Medium Instance
    description: Stable environment with 1.5 cpu / 2 GB ram
    kubespawner_override:
      cpu_limit: 1.5
      cpu_guarantee: 1.25
      mem_limit: 2G
      mem_guarantee: 2G
      image: quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334
  dask_worker:
    Small Worker:
      worker_cores_limit: 1
      worker_cores: 1
      worker_memory_limit: 1G
      worker_memory: 1G
      image: quansight/qhub-dask-worker:1abd4efb8428a9d851b18e89b6f6e5ef94854334
    Medium Worker:
      worker_cores_limit: 1.5
      worker_cores: 1.25
      worker_memory_limit: 2G
      worker_memory: 2G
      image: quansight/qhub-dask-worker:1abd4efb8428a9d851b18e89b6f6e5ef94854334
environments:
  environment-default.yaml:
    name: default
    channels:
    - conda-forge
    - defaults
    dependencies:
    - python=3.8
    - ipykernel
    - ipywidgets
    - dask==2.14.0
    - distributed==2.14
    - dask-gateway=0.6.1
    - numpy
    - numba
    - pandas
