name: "Docker Image Build"

on:
  push:
    branches:
      - master
    paths:
      - "image/**"
      - ".github/workflows/image.yaml"

jobs:
  build:
    name: QHub Build Dockerfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Build, Tag, and Push Image
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/tl-test-project-${{ matrix.dockerfile }}
        run: |
          docker build -f image/Dockerfile.${{ matrix.dockerfile }} -t $IMAGE_NAME:$IMAGE_TAG image
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

